### ISSUE TITLE
Missing variable to store exception causes error

### ISSUE THREAD

**Issue by donnchawp** [shawnhooper/twitter-archive-to-wp#12]
On the following line in import-twitter-command.php there's a missing variable that causes a PHP error in PHP 7.4. Adding $e to it fixes the problem.

https://github.com/shawnhooper/twitter-archive-to-wp/blob/142c35428234c5595fd4085c05026a8ae7183ddc/classes/import-twitter-command.php#L59

**Comment by shawnhooper** [comment]
Confirmed via Mastodon that this was fixed. Closing.
