### ISSUE TITLE
Missing directory name in image paths if site in not in /

### ISSUE THREAD

**Issue by donnchawp** [shawnhooper/twitter-archive-to-wp#13]
I tested with a site in a directory, and the path to images in tweets didn't have the directory in it.

Site was in https://example.com/test-site/, but image paths were /wp-content/uploads/twitter-archive/tweets_media/.... and missing the "/test-site" part.

**Comment by shawnhooper** [comment]
Confirmed via Mastodon that this was fixed. Closing.
