### ISSUE TITLE
t.co short links aren't being replaced

### ISSUE THREAD

**Issue by donnchawp** [shawnhooper/twitter-archive-to-wp#15]
t.co links aren't being converted to their expanded URLs because of a small bug.
The following line of code uses $tweet->full_text when it should use $tweet_text. Replace that and t.co links become clickable.

https://github.com/shawnhooper/twitter-archive-to-wp/blob/3fdcd834a584fe1d0e43887bc36c1ec0cc636d02/classes/import-twitter-command.php#L172

**Comment by shawnhooper** [comment]
@donnchawp Good catch.  Fixed!
