### ISSUE TITLE
Error: Error while reading account.js: Syntax error

### ISSUE THREAD

**Issue by matirosero** [shawnhooper/twitter-archive-to-wp#16]
As soon as I try to run the import, I get:

`Error: Error while reading account.js: Syntax error`

That's all it says.

**Comment by matirosero** [comment]
Never mind, it was because I moved the ENTIRE data directory into wp-content/tweet-archive, not just the files

**Comment by shawnhooper** [comment]
@matirosero Glad you figured it out. If you run into any other problems let me know!
