### ISSUE TITLE
Perhaps use warning instead of error when file is not found

### ISSUE THREAD

**Issue by paulvanbuuren** [shawnhooper/twitter-archive-to-wp#2]
I am very very grateful for this plugin, Shawn. Thank you so much.

I would suggest that NOT finding a media file locally does NOT break the import process. In order for my import to run completely, I changed WP_CLI::error to WP_CLI::warning in classes/import-twitter-command.php#L167
https://github.com/shawnhooper/twitter-archive-to-wp/blob/40ca67c212df541c2e3382cdeda457f11206a3f3/classes/import-twitter-command.php#L167

**Comment by shawnhooper** [comment]
Hey @paulvanbuuren!  Thanks for the suggestion.  I've implemented it in today's update.
