### ISSUE TITLE
Script said "Success: Import Complete - 61583 tweets processed, skipped" but no entries...

### ISSUE THREAD

**Issue by janngobble** [shawnhooper/twitter-archive-to-wp#5]
I'm on DreamHost - with the most recent WordPress update: 6.1.1, accessing this through ssh command line.

My archive has tweets-part1.js, tweets-part2.js as well as tweets.js, so I copied the js file to tweets.json and ran it only on the first one.
Got this: (snipped to show last 15 lines or so...)
`wp import-twitter 1`

```
Starting Import of 61583 tweets
Processing Tweet 1 of 61583
Processing Tweet 2 of 61583
...
Processing Tweet 61570 of 61583
Success: Found Media (photo): 1586700136234815488-FgR27cCXoAM_XFM.jpg
Processing Tweet 61571 of 61583
Processing Tweet 61572 of 61583
Processing Tweet 61573 of 61583
Processing Tweet 61574 of 61583
Processing Tweet 61575 of 61583
Processing Tweet 61576 of 61583
Success: Found Media (photo): 1586708092032532481-FgUejBiXkAAk0Vd.jpg
Processing Tweet 61577 of 61583
Processing Tweet 61578 of 61583
Processing Tweet 61579 of 61583
Processing Tweet 61580 of 61583
Processing Tweet 61581 of 61583
Processing Tweet 61582 of 61583
Processing Tweet 61583 of 61583
Success: Import Complete - 61583 tweets processed, skipped
```

BUT nothing is entered in the db.

It had to see the json and the media cos it counted up and it found media...

Wondering why?

**Comment by janngobble** [comment]
Well, sideline this for the moment. Trying something. I think I just didn't realize they were posted under post_type "birdsite_tweet" and am now trying to figure out how to make that display in my wordpress feed.

More info soon...

**Comment by shawnhooper** [comment]
@janngobble interesting note about the split tweets.js file. I guess I didn't have enough tweets to trigger the splitting to take place. I'll see about writing a patch for that. Once I do, would you mind testing for me?

To see the posts on your site, try the /tweets/ URL. See if they appear there. There's no stylizing of how they appear yet. Still something to be done.

**Comment by janngobble** [comment]
> @janngobble interesting note about the split tweets.js file. I guess I didn't have enough tweets to trigger the splitting to take place. I'll see about writing a patch for that. Once I do, would you mind testing for me?
> 
> To see the posts on your site, try the /tweets/ URL. See if they appear there. There's no stylizing of how they appear yet. Still something to be done.

I have tweets from 2007 so - yes - I have tweets.js, tweets-part1.js, and tweets-part2.js. (I know, I know...get OFF of social media)

So, re: seeing the posts: If I change post_type to something else, can I just have this plugin import my tweets as posts?

All I really want is for all my tweets (and later my toots) to appear on my website.  IF this is as easy as editing "default post_type" in wordpress, that's what I'd love...then your import tool can continue to work as per normal. BUT if not, maybe with an extra argument "use-main-post=1" or something in the cli? I can edit the post_type in the php, but I didn't know if it would have repercussions - and what to make it read to in order to appear in "posts" section and then on the main site - as I don't blog...i microblog and therefore my site will be all tweets.

The titles seem to be cut off w/"..."  too... is that a shortcoming to the database not allowing all ~280chars of a tweet (plus the extended URLs (when converted from t.co)? Or is it that the titles get auto-shortened?

Meanwhile; busy running the delete phase of 161k tweets in order to re-import to make sure I get them all.

ps: if script is run twice, does it actually duplicate tweets or is it smart enough not to do that? 

NOT asking for new features. Just wondering.

Thanks!
And yes, I'll test any new features (incl multiple .js file imports)

Oh, also? Just as a hint when you go to merge multiple js files, the copying of tweets-part1.js to tweets.js did NOT WORK as tweets.js' variable is: `window.YTD.tweets.part0 = [{}]` while tweets-part1.js is `window.YTD.tweets.part1 = [{}]` and tweets-part2.js is `window.YTD.tweets.part2 = [{}]` ...etc

also, simply combining the js hashes from part1 and part2 into the main file's `window.YTD.tweets.part0 = [{}]` results in DreamHost killing the process - for causing too high resource-usage! 😂

Oh, well...I tried. 😉

**Comment by shawnhooper** [comment]
@janngobble See the "issue-5" branch:  https://github.com/shawnhooper/twitter-archive-to-wp/tree/issue-5 

This *should* based on your description add the multipart file support.  I've also added some code that will hopefully help with the memory issue on Dreamhost.  Let's see.... 

Would you mind testing it?

**Comment by janngobble** [comment]
Testing now... deleting previously imported tweets first so i have a blank slate to test with.

btw: I have too many posts/tweets to delete using the one-liner you gave:

`wp post delete $(wp post list --post_type='birdsite_tweet' --format=ids) --force`
(and no, the first one didn't work either)

I had to use:
`wp post delete $(wp post list --post_type='birdsite_tweet' --format=ids --posts_per_page=50000) --force`

Will let you know soon if it works.
Thanks for the quick adaptations to the scripts!

**Comment by janngobble** [comment]
> 

Whelp... I tried. After about 3 minutes of chugging it came back with this: (`gopher` is the DreamHost server name)

```
[gopher]$ wp import-twitter 1


Yikes! One of your processes (php, pid 52693) was just killed for excessive resource usage.
Please contact DreamHost Support for details.


Killed
[gopher]$ 

```
ps: I **know** this means ram and not "cpu time", etc as the "delete tweets" run for hours and the system does not kill it. (yes, I have huge amount of tweets).


Maybe if we can get a flag for the command line a la:

no flag: it processes `tweets.js`
--tweetfile 1 : it processes `tweets-part1.js`
--tweetfile 2 : it processes `tweets-part2.js`
...etc


The reason I think this would be good is that I'm pretty sure twitter exports a tweet and any replies in the same .js file...thus we wouldn't be unlinking a tweet from it's reply accidentally. Also because I ran the original (release) script with the three diff files and it didn't get killed by DreamHost, I know that the MOST twitter puts in a single file is okay for this script to run through.

Those are just suggestions.

Thanks again, Shawn!

**Comment by shawnhooper** [comment]
@janngobble Can you try reprocessing your 3 files again?  It should now handle them each on their own one after the other. 

I'm also adding a new _tweet_id meta_key to both the posts and the comments in order to be able to process an archive again and not create duplicates.  (That part still to be written)

**Comment by janngobble** [comment]
Just redownload the zip archive listed here? ie: diff commit, but same “issue-5”, right?

https://github.com/shawnhooper/twitter-archive-to-wp/tree/issue-5 <https://github.com/shawnhooper/twitter-archive-to-wp/tree/issue-5>

**Comment by shawnhooper** [comment]
@janngobble no, on the main branch. I made some fake data on my local.

**Comment by janngobble** [comment]
Oh, okay. doing it now…

The first file is processing just fine. I’ll let you know later when this one is done and it moves to the next.

Thanks!!!!

**Comment by shawnhooper** [comment]
Release 2.0.0 skips entries that are already imported.
