### ISSUE TITLE
Please use the same tag system you use for hashtags for ticker symbols...

### ISSUE THREAD

**Issue by janngobble** [shawnhooper/twitter-archive-to-wp#6]
Twitter users had a habit of tagging companies in twitter by their ticker symbols, ie: "$JCP down 5.00 today"

Is it possible to add the "JCP" (ticker symbols) in these tweets to the tag table like you do the #hashtags (I think you birdsite_hashtags them). I have thousands of tweets with ticker "$" symbols in them.

Thanks!

Jann

**Comment by shawnhooper** [comment]
Absolutely.  I'm thinking the stored taxonomy value would include the $ before the ticket symbol.  Would you agree?

**Comment by janngobble** [comment]
I would agree... as if I was searching for a ticker symbol in someone's tweet archive, I would use $ as well.

Thanks for thinking this is a decent idea.

One other thing is this: Is it up to the import script or the theme to highlight links...cos they just show up as text right now. If it is the theme's job I'll look into it on that end.

**Comment by shawnhooper** [comment]
@janngobble I just published an update that includes the symbols being imported as hashtags. 

They do not link to anything on the front end at the moment.

**Comment by janngobble** [comment]
Thanks!
