### ISSUE TITLE
Would be nice if links in Tweets worked

### ISSUE THREAD

**Issue by rosswintle** [shawnhooper/twitter-archive-to-wp#7]
Hey Shawn,

This is very awesome. I just tried it out locally. Really good stuff. Thanks for making this!!

Looks like you properly resolve URLs, but I'd love it if the imported Tweets has these as actual links.

This would, I suppose, require the tweets to be imported to `post_content` rather than `post_title` (I... think???)

What do you think? I'm happy to PR this.

**Comment by shawnhooper** [comment]
They do now! :)

**Comment by shawnhooper** [comment]
Thanks for the PR
